### ISSUE TITLE
Missing projects

### ISSUE THREAD

**Issue by mscharling** [eulertour/eulerv2#21]
Hi,

I was using the first version of EulerTour.com to make animations and I didn't recognize that you were going to build a second version. How do I login and get my old projects?

**Comment by eulertour** [comment]
Sorry about that, I never expected people to use real projects on the old site. If you email me or message me on [the manim discord](https://discord.gg/5FGf7u) I can get them to you (the discord will be faster). I plan to make them available online again, but it could be a while before that happens.

**Comment by mscharling** [comment]
Sorry I might have been to slow to find you on Discord. It says the invitation is expired. Could you link me again?

**Comment by eulertour** [comment]
Sorry, this one should do it. https://discord.gg/mMRrZQW
