### ISSUE TITLE
not responsive in mobile

### ISSUE THREAD

**Issue by parmeshpatidar** [eulertour/eulerv2#22]
Hi, 
I was reading docs on **eulerv2** and I appreciate your work.
But website is not responsive on mobile devices when we go to [https://eulertour.com/docs](url).

**Comment by eulertour** [comment]
I updated the styling to be responsive on mobile but the editor itself still isn't compatible with mobile devices.

**Comment by eulertour** [comment]
I've opened #23 to track the updated issue.
